# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_ref',
                'doc_host': 'https://Charts-n-Crafts.github.io',
                'git_url': 'https://github.com/Charts-n-Crafts/nbdev_ref',
                'lib_path': 'nbdev_ref'},
  'syms': {'nbdev_ref.core': {'nbdev_ref.core.foo': ('quarto_commands.html#foo', 'nbdev_ref/core.py')}}}
